w11/d04/Classwork/puppy/puppy/config/routes.rb
Rails.application.routes.draw do
  resources :puppy_dog_twos

end

w11/d04/Classwork/puppy/puppy/app/models/puppy_dog.rb
class PuppyDog < ActiveRecord::Base
end

w11/d04/Classwork/puppy/puppy/app/models/puppy_dog_two.rb
class PuppyDogTwo < ActiveRecord::Base
end

w11/d04/Classwork/puppy/puppy/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

w11/d04/Classwork/puppy/puppy/app/controllers/puppy_controller.rb
class PuppyController < ApplicationController
end

w11/d04/Classwork/puppy/puppy/app/controllers/puppy_dog_twos_controller.rb
class PuppyDogTwosController < ApplicationController
  before_action :set_puppy_dog_two, only: [:show, :edit, :update, :destroy]

  # GET /puppy_dog_twos
  # GET /puppy_dog_twos.json
  def index
    @puppy_dog_twos = PuppyDogTwo.all
  end

  # GET /puppy_dog_twos/1
  # GET /puppy_dog_twos/1.json
  def show
  end

  # GET /puppy_dog_twos/new
  def new
    @puppy_dog_two = PuppyDogTwo.new
  end

  # GET /puppy_dog_twos/1/edit
  def edit
  end

  # POST /puppy_dog_twos
  # POST /puppy_dog_twos.json
  def create
    @puppy_dog_two = PuppyDogTwo.new(puppy_dog_two_params)

    respond_to do |format|
      if @puppy_dog_two.save
        format.html { redirect_to @puppy_dog_two, notice: 'Puppy dog two was successfully created.' }
        format.json { render :show, status: :created, location: @puppy_dog_two }
      else
        format.html { render :new }
        format.json { render json: @puppy_dog_two.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /puppy_dog_twos/1
  # PATCH/PUT /puppy_dog_twos/1.json
  def update
    respond_to do |format|
      if @puppy_dog_two.update(puppy_dog_two_params)
        format.html { redirect_to @puppy_dog_two, notice: 'Puppy dog two was successfully updated.' }
        format.json { render :show, status: :ok, location: @puppy_dog_two }
      else
        format.html { render :edit }
        format.json { render json: @puppy_dog_two.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /puppy_dog_twos/1
  # DELETE /puppy_dog_twos/1.json
  def destroy
    @puppy_dog_two.destroy
    respond_to do |format|
      format.html { redirect_to puppy_dog_twos_url, notice: 'Puppy dog two was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_puppy_dog_two
      @puppy_dog_two = PuppyDogTwo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def puppy_dog_two_params
      params.require(:puppy_dog_two).permit(:name, :breed, :cuteness)
    end
end

w11/d04/Classwork/puppy/puppy/app/helpers/application_helper.rb
module ApplicationHelper
end

w11/d04/Classwork/puppy/puppy/app/helpers/puppy_dog_twos_helper.rb
module PuppyDogTwosHelper
end

w11/d04/Classwork/puppy/puppy/app/helpers/puppy_helper.rb
module PuppyHelper
end

w11/d04/Classwork/puppy/puppy/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Puppy</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

w11/d04/Classwork/puppy/puppy/app/views/puppy_dog_twos/_form.html.erb
<%= form_for(@puppy_dog_two) do |f| %>
  <% if @puppy_dog_two.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@puppy_dog_two.errors.count, "error") %> prohibited this puppy_dog_two from being saved:</h2>

      <ul>
      <% @puppy_dog_two.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :breed %><br>
    <%= f.text_field :breed %>
  </div>
  <div class="field">
    <%= f.label :cuteness %><br>
    <%= f.number_field :cuteness %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

w11/d04/Classwork/puppy/puppy/app/views/puppy_dog_twos/edit.html.erb
<h1>Editing puppy_dog_two</h1>

<%= render 'form' %>

<%= link_to 'Show', @puppy_dog_two %> |
<%= link_to 'Back', puppy_dog_twos_path %>

w11/d04/Classwork/puppy/puppy/app/views/puppy_dog_twos/index.html.erb
<h1>Listing puppy_dog_twos</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Breed</th>
      <th>Cuteness</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @puppy_dog_twos.each do |puppy_dog_two| %>
      <tr>
        <td><%= puppy_dog_two.name %></td>
        <td><%= puppy_dog_two.breed %></td>
        <td><%= puppy_dog_two.cuteness %></td>
        <td><%= link_to 'Show', puppy_dog_two %></td>
        <td><%= link_to 'Edit', edit_puppy_dog_two_path(puppy_dog_two) %></td>
        <td><%= link_to 'Destroy', puppy_dog_two, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Puppy dog two', new_puppy_dog_two_path %>

w11/d04/Classwork/puppy/puppy/app/views/puppy_dog_twos/new.html.erb
<h1>New puppy_dog_two</h1>

<%= render 'form' %>

<%= link_to 'Back', puppy_dog_twos_path %>

w11/d04/Classwork/puppy/puppy/app/views/puppy_dog_twos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @puppy_dog_two.name %>
</p>

<p>
  <strong>Breed:</strong>
  <%= @puppy_dog_two.breed %>
</p>

<p>
  <strong>Cuteness:</strong>
  <%= @puppy_dog_two.cuteness %>
</p>

<%= link_to 'Edit', edit_puppy_dog_two_path(@puppy_dog_two) %> |
<%= link_to 'Back', puppy_dog_twos_path %>